### DISCUSSION TITLE
Comment System in Automad! 💬

### DISCUSSION THREAD

**Discussion by SuitDeer** [automadcms/discussions#53] [Show and tell]
Hello,
is there a Comment system planned for automad 2.0?

**Comment by Artiom-M** [comment]
I don't think there is a commenting system but I plan to integrate with this one https://isso-comments.de/docs/reference/installation/

**Comment by SuitDeer** [comment]
I have now tested adding the [comentario](https://comentario.app/en/) commenting system into automad demo and it looks awesome

docker compose for the 
```yaml
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: comentario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./comentariostack/postgres-data:/var/lib/postgresql/data

  app:
    image: registry.gitlab.com/comentario/comentario:v3.13.1
    environment:
      BASE_URL: https://comentario.hostlab.tech/
      SECRETS_FILE: "/secrets.yaml"
    ports:
      - "8082:80"
    volumes:
      - ./comentariostack/comentario/secrets.yaml:/secrets.yaml:ro
    depends_on:
      - db
```

Integration of comentario into a automad page:

![automad2-cms_add-content-before-footer- (Kopieren)](https://github.com/user-attachments/assets/df1042e5-8ee0-47b6-a4d1-6255700d06a1)


---

Result of the integration:

![grafik](https://github.com/user-attachments/assets/5245f2c2-1210-488b-8af9-42a0ea4b86a0)
